apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - pod-disruption-budget.yaml

images:
  - name: ghcr.io/jesusblazquez/bank-ledger-k8s
    newTag: v1.0.0

patches:
  - path: app-prod-patch.yaml
